### ISSUE TITLE
Can't access the UI when defining it on a different port

### ISSUE THREAD

**Issue by ilopmar** [yugabyte/charts#111]
I'm trying to configure the UI on a different port than `7000` with something like:

```yaml
serviceEndpoints:
  - name: "yb-master-ui"
    type: LoadBalancer
    app: "yb-master"
    ports:
      http-ui: "80"
```

I can install the chart and I see the services are using the new port. When I connect to it in the browser, it immediately fails with a "connection refused" error.

With this patch it works properly but I'm not 100% sure if any other thing is needed.

```diff
--- ../../yugabyte/templates/service.yaml	2021-08-28 14:52:55.000000000 +0200
+++ service.yaml	2021-10-25 16:19:37.000000000 +0200
@@ -95,6 +95,7 @@
     {{- range $label, $port := $endpoint.ports }}
     - name: {{ $label | quote }}
       port: {{ $port }}
+      targetPort: 7000
     {{- end}}
   selector:
     {{- include “yugabyte.appselector” ($appLabelArgs) | indent 4 }}
```
