### ISSUE TITLE
Missing Namespace in Service resources

### ISSUE THREAD

**Issue by carhartl** [yugabyte/charts#151]
The namespace that can be passed as Helm value isn't picked up in the Service resources part of the chart:

```
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.oldNamingStyle | ternary $endpoint.name (printf "%s-%s" (include "yugabyte.fullname" $root) $endpoint.name) | quote }}
  annotations:
...
```

=>

```
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Values.oldNamingStyle | ternary $endpoint.name (printf "%s-%s" (include "yugabyte.fullname" $root) $endpoint.name) | quote }}
  namespace: "{{ $root.Release.Namespace }}"
  annotations:
...
```

I was expecting all resources to be part of the namespace I'm specifying in the chart.

Similar to #64

**Comment by carhartl** [comment]
Workaround in my case:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: yugabyte
    releaseName: yugabytedb
    repo: https://charts.yugabyte.com
    version: 2.17.0
    namespace: yugabytedb-system
    valuesInline:
      replicas:
        master: 1
        tserver: 1
      resource:
        master:
          requests:
            cpu: 0.5
            memory: 0.5Gi
        tserver:
          requests:
            cpu: 0.5
            memory: 0.5Gi
patches:
  - patch: |-
      - op: add
        path: /metadata/namespace
        value: yugabytedb-system
    target:
      version: v1
      kind: Service
      name: yb-.*
```
