### ISSUE TITLE
TLS + authCredentials leads to yugabyte-setup-credentials job failure

### ISSUE THREAD

**Issue by ghaskins** [yugabyte/charts#168]
# Versions

- helm chart: 1.18.0
- yugabyte: 2.18.0.1-b4

# Details

The following configuration leads to the inability for the yugabyte-setup-credentials job to finish successfully

```yaml
authCredentials:
  ycql:
    password: xxx
    user: yugabyte
tls:
  enabled: true
  nodeToNode: true
  clientToServer: true
  insecure: false
  certManager:
    enabled: true
```

I have confirmed that enabling only TLS or only authCredentials does work, but the combination of the two together fails.
