### ISSUE TITLE
Add TLS certicate as a kubernetes secret 

### ISSUE THREAD

**Issue by sstubbs** [yugabyte/charts#18]
From what I understand the chart receives the certificate details via chart values. It would better to use a kubernetes secret which can be created by certmanager and rotated.

**Comment by rkarthik007** [comment]
cc @iSignal @nchandrappa

**Comment by sstubbs** [comment]
I've tried creating a certmanager certificate like the following:
```
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: production-0-ybdb
spec:
  secretName: production-0-ybdb-secret
  issuerRef:
    name: selfsigned
  commonName: certmanager
  dnsNames:
  - yb-master-0
  - yb-master-0.yb-masters.ybdb.svc.cluster.local
  - yb-masters
  - yb-masters.ybdb.svc.cluster.local
  - yb-tserver-0
  - yb-tserver-0.yb-tservers.ybdb.svc.cluster.local
  - yb-tservers
  - yb-tservers.ybdb.svc.cluster.local
  ipAddresses:
  - 127.0.0.1
```
Then copying the base64 values into the helm chart but it doesn't work.
