### ISSUE TITLE
helm template fails with readiness probe enabled and ysql_enable_auth: true

### ISSUE THREAD

**Issue by amannijhawan** [yugabyte/charts#202]
values.yaml overrides
```

gflags:
  tserver:
    ysql_enable_auth: true
tserver:
  readinessProbe:
    enabled: true
```

Command line:
```
helm template yugabytedb/yugabyte -f values.yaml > yugabyte.yaml
```
Observed behavior
```
Error: template: yugabyte/templates/service.yaml:93:63: executing "yugabyte/templates/service.yaml" at <include "yugabyte.tserver.readinessProbe" $root>: error calling include: template: yugabyte/templates/_helpers.tpl:574:54: executing "yugabyte.tserver.readinessProbe" at <eq .Values.gflags.tserver.ysql_enable_auth "true">: error calling eq: incompatible types for comparison
```
