### ISSUE TITLE
Add loadBalancerClass in serviceEndpoints

### ISSUE THREAD

**Issue by JulienPrechey** [yugabyte/charts#204]
Hi, 

Would it be possible to add loadBalancerClass parameter in serviceEndpoints ?

```
serviceEndpoints:
  - name: "yb-master-ui"
    type: ClusterIP
    loadBalancerClass: nginx
```

Thanks,
