### ISSUE TITLE
Add Ingress and ServiceMonitor helm chart support

### ISSUE THREAD

**Issue by sergeyshaykhullin** [yugabyte/charts#7]
There is a common practice to add ingress and prometheus operator ServiceMonitor support for web ui and crilical systems

```
ingress:
  enabled: true
  hosts: [...]
  tls: [...]
  annotations: [...]
  ...etc

monitoring/prometheus/...:
  serviceMonitor:
    enabled: ...
    ...etc
```

There are some examples:
- https://hub.helm.sh/charts/argo/argo-cd
- https://hub.helm.sh/charts/stable/grafana
- https://hub.helm.sh/charts/jaegertracing/jaeger-operator
- https://hub.helm.sh/charts/bitnami/prometheus-operator
- https://hub.helm.sh/charts/stable/rabbitmq-ha
- https://hub.helm.sh/charts/jetstack/cert-manager
- https://hub.helm.sh/charts/stable/nginx-ingress
- https://hub.helm.sh/charts/loki/loki
- https://hub.helm.sh/charts/loki/promtail
- https://hub.helm.sh/charts/stable/redis-ha
